before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: W6NbNb+8ZxMhve3cHZv0SIffE0bfyResWE+wzImFK3EWJJWOyz0IRyn42QvOb6pxK+Xhj9Y2WZ5OrQ+isnsB/GBbCIM2u3trurSaHUBUUumHXAh56JAQ4U/LR9KlrrhWQJ04FN+QgPiUnOjM4KqM1X6Mx0eC9wHMNPOrKN5y6VUiTCdnGiGWSvSZpaR+wSSZ0WHZwL4BdAg+Oe36RrOnq7VxZRHS1KtRJSPru4PwyF6TPGGcz+v8TnU2IZsis2/Tl5qXzxawBk0arvkCuIjvYLUT9gSqVkFDmTvRSZLwt7S1xDe2RD5psHzoW8M3/O/moxJ9EuGhqC3BnYwzx+r2LiC5xetEyB+D7Nd1Uy35Dw0aAwCkJE1LQ0nybqvoX5weI6mF3gt5Rt/Na8rA3oo2slUOsjT2bS8ZOpmRQ1VR2i/6hWRC9aIiE/b0giQ3u5eTH9oMj3r/YJtxmd9z8aseOXofl85MdE0nnZEcYGShukmrau5mFq6mlVmmaYVtrR6U4/HB1stAWgfY1otGA610TfQhMgz4gXVvT1rdYBets+DBhRvnQpyMIPT3lckSjz1v7oKoorqh38vnZYXK91fvWsa6bHcibC1XwctHr2FpJFB5w4PJHetLnDzN2ZocQWly4Xa+6wGvA5rQXpKJ9aRY7ZQU0caQ4EyOrikJv8wL8Ps= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
